#!/bin/bash

# Sample: Show girl face ASCII from screenshot in tool output
# This would be added to lib/common.sh

show_svetri_banner_with_screenshot() {
    # Load the ASCII art from the screenshot
    local screenshot_art=$(cat << 'EOF'
.....                                                       
...............                                             
..........                                                  
........                                                    
.......                        ..                           
.......                       .'.     .....                 
......                 ..... ..;,.   . ....                 
......               ..';lodocclcccc:'....                  
.....               ..',:oxkOOOkOO0KKxl:'.                  
....                ..',:oxkO0KKKXXNNOOOd;...               
 ..                 ..',:lxO0KKKKXXNNXOXO:.....             
                    ..',:oxO0KKKKXXNNXOX0; .....            
                    ...';lxO000KXXNNNNKOO,  ....            
                   .......:dO0000kdodk0Od.  .....           
                 ... ...'..,oO0Oo,.,:kK0o .  ....           
                 ..''.',,'..lKXOc;,odlOX:  .......          
                 ..,:clc:,..dNNN0kk0XNN0.  ........         
                  .';looc..;OXXXXXNNNNX;   ........         
                  ..;coo:..l0XX0OKXXXXo    .........        
                   .,::;,',lxKXXOOKK0l.     ........        
                   ..;;...;lokO0kk0k,       ........        
                     .'',;codkO0Od,          .......        
                . ..  ..;lx0KX0x:.           ........       
 .....    .        ..   .;odxxdl;.           ...'.....      
....'..   .        ......,dxxkkdc.            ...'....      
',,',,'.  .      .. ...'',xkkkkd:.             ...'''..     
ll:,;,,.          . ...',;dkkkkxc..    .    .   ...'''.     
ooddkko;..         ....,,:ok00Okl;.    .   ...   .'.''..    
oOO0K0d,.          ....',:okOkxdoc'.  ..  .....  .''''...   
kxKKKOl..          . ...,,lx0KK0x;.. ...  ...   ....,,...   
KKOXKd,.       ..... ....,:ld0K0l'... .. ..........,',...   
XX000d.         .........';cxKKo'...  .....   ....,,,;...   
XXKxOl.          .......'.;lKKx;...   ....  .....'';;:..    
XX0dx;.  ... .. ........',cx0kl,..   .....  ..'..',::c'     
XKkcl'... .. ..........:lcloddd;..  .... . ..';;,';:cc,.    
KOd;;..  .........''',;cl:coO0k;..   ........;:c;;::cc,.    
Kko,..   .. .....''',;;clcd0XXx'..   ........;:c::lllcc..    
KOc...  .........'',;:lkddOKX0;..........'';:::ccolll:...   
d0d.. ...........',;:lldOKXNX;...,,,,''',;:llc:dxdlll;..    
ccd.   .........'',;:cxOKXNXk...,::,,,,,;:colocdkolcc'..    
EOF
    )
    
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║                                                                ║"
    echo "║  S V E T R I  -  GitHub Security Intelligence Tool            ║"
    echo "║                                                                ║"
    echo "║  Girl Face (from your screenshot):                             ║"
    echo "║                                                                ║"
    echo "$screenshot_art" | sed 's/^/║  /'
    echo "║                                                                ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
}

# Test the function
show_svetri_banner_with_screenshot
